### ISSUE TITLE
Toggle language selection

### ISSUE THREAD

**Issue by d33pspace** [d33pspace/Internationalization#3]
The site will be available only in US English and Simplified Chinese (en-US and zh-CN). I'd like simple toggle in the layout page (top) to allow users to change their language preference and remain on the same page. Please note based on the best way to handle the user's currency preference (independently of their language preference) this may need to change slightly . . . perhaps two toggles or a drop-down menu?

**Comment by d33pspace** [comment]
I see the drop-down which is great. I'd like to keep it for demonstration purposes, but since there are only two options, (1) I'd also like a simple link that changes the language selection directly. (2) You may have considered this already and have this solved, but I wonder if we also need a similar link that toggles the currency from USD to CNY. (Currency preference will not always correspond to language preference.)

**Comment by malisancube** [comment]
That is correct, language does not correspond to currency. There is an entity for Currency, however it seems it maybe a better design to have the default currency selectable by the user and saved as part of their profile. May I proceed and add that?

**Comment by d33pspace** [comment]
Note that I believe there is a "culture" setting related with the language setting which determines the format of numbers and dates. But you're right, the currency selection is still independent of this. I think there should be a link to toggle the currency selection between USD and CNY (and possibly in the future other currencies) and yes, I think it should be saved as part of their profile (also cookie?).
