### ISSUE TITLE
Summary of requirements

### ISSUE THREAD

**Issue by d33pspace** [d33pspace/Internationalization#6]
- [ ] Demonstrate how to display text initially according to language/culture settings of browser (either en-US or zh-CN. Note that we need samples of text strings from Controller, View and database.

- [ ] Users can change the language using a link. Provide samples of both drop-down menu (as currently implemented) and a simple link which changes the language directly (because there are currently only two options). 

- [ ] Similarly users can change currency between USD and CNY. Again, provide samples of drop-down menu and link. Currency may also be handled by Controller, View or database.

- [ ] Currency and language selections are saved in the user's profile (database) and as a cookie. For repeat visitors, the priority of browser setting, database profile and cookie selection should be handled according to typical standards.

**Comment by malisancube** [comment]
Currently the translations strings are stored in as *.resx files. You would like them to be in a database? The downside is making many database calls for all translations. A cache may be good for that. 

1) Currency is stored on the user's profile. This seems to make more sense as the use is expected to most likely use the same language. The default currency for the user is based on the region where they are.

2) On selecting language using a link, do you want to have any url support language as part of the querystring? e.g. http://localhost:5000/currency/create?culture=en-US

3) About samples, do you wan them as separate projects?

4) Could not get the last requirement. The standards?

**Comment by d33pspace** [comment]
1. Default currency selection by region is perfect. Mainland China should be CNY, all other regions should be USD. But if the currency is changed by the user shouldn't it be stored both in their profile and as a cookie? 

2. Thank you for asking. I don't think language as part of the query string is necessary. Only default from browser, then any changes made stored by database and cookie.

3. Do not need separate projects, both types of language selectors together is fine. 

4. I believe this last requirement is probably redundant. Don't worry about it.

**Comment by d33pspace** [comment]
By the way, yes, the bulk of the translations will be in *.resx files, but occasionally we will need to store strings in a database. I was mainly interested in a demonstration of the proper way to handle this with multiple languages involved, but if it's adding time or complexity to the project, let's leave it out for now. It's not an immediate need. I'd like to wrap these projects up as soon as possible. :)

**Comment by malisancube** [comment]
OK. What is the convenient time for us to have a Skype? I would like to close this and we have a quick feedback session. My skype handle is malisa.ncube
